config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.console:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.console.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-lime-hare.sh
        container: qc.acc_droopy-mustard-iguana
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.console find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-sepia-tortoise.sh
        container: qc.doc_jumpy-aquamarine-dingo
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-white-okapi.sh
        container: qc.doc_blurry-mustard-alligator
      github.com/cessda/cessda.cmv.console markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-denim-insect.sh
        container: qc.doc_cozy-brass-lizard
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.console licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-green-ant.sh
        container: qc.lic_hasty-amaranth-sparrow
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.console cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cardinal-bison.sh
        container: qc.met_scummy-green-skunk
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.console checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-pink-giraffe.sh
        container: qc.sty_cloudy-thistle-caracal
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.console get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-apricot-civet.sh
        container: qc.ver_ugly-magenta-wombat
timeout: 5400
