config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.console:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.console.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-burgundy-donkey.sh
        container: qc.acc_squeaky-cerulean-earwig
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.console find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-heliotrope-stoat.sh
        container: qc.doc_greasy-cyan-cougar
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-mauve-saola.sh
        container: qc.doc_geeky-mustard-urchin
      github.com/cessda/cessda.cmv.console markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cardinal-saola.sh
        container: qc.doc_muggy-champagne-dugong
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.console licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-apricot-jackal.sh
        container: qc.lic_stinky-auburn-maltese
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.console checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-razzmatazz-cougar.sh
        container: qc.sty_fuzzy-viridian-cassowary
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.console get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-olivine-llama.sh
        container: qc.ver_skimpy-denim-skunk
timeout: 5400
